# Python Basics for Analytics

## Sorted() & zip()

In [46]:
a = [-1, -5, 3, -33]
b = ['x', 'y', 'z', 't']

print("-----sorted()------")
print(sorted(a))
print(sorted(a, key=abs, reverse=True))

print("-----zip()------")
z = list(zip(a, b))
print(z)

c, d = zip(*z)
print(c, d)

-----sorted()------
[-33, -5, -1, 3]
[-33, -5, 3, -1]
-----zip()------
[(-1, 'x'), (-5, 'y'), (3, 'z'), (-33, 't')]
(-1, -5, 3, -33) ('x', 'y', 'z', 't')


## Numpy

In [55]:
import numpy as np

print("-----rand()------")
print(np.random.rand())    # Generage a single random number in range [0,1)
print("----")
print(np.random.rand(3,2)) # Generate a matrix of random numbers in range [0,1) with shape (3,2)

print("-----randint()------")
print(np.random.randint(5, 15, 2))
print("----")
print(np.random.randint(5, 15, (3,2)))

print("-----choice()------")
array = np.array([1,2,3,4,5]) 
print(np.random.choice(array, 10, replace=True)) # replace=True means the same value can be sampled more than once
print("----")
print(np.random.choice(array, 3, replace=False)) # replace=False means the same value can’t be sampled more than once

print("-----shuffle()------")
np.random.shuffle(array)
print(array)

-----rand()------
0.7316961330873843
----
[[0.54876532 0.66840215]
 [0.98741047 0.33870392]
 [0.5936519  0.20722547]]
-----randint()------
[13 12]
----
[[ 6 12]
 [13  5]
 [11  8]]
-----choice()------
[4 3 2 1 5 4 2 4 4 2]
----
[1 3 4]
-----shuffle()------
[3 5 2 4 1]


## Scipy